import { createHash } from 'node:crypto'
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { chromium } from 'playwright'
import { build, readCatalog, root } from './build.mjs'
import { createServer } from './serve.mjs'

const buildReport = await build()
const { catalog } = await readCatalog()
const directory = path.join(root, 'dist/exports')
await mkdir(directory, { recursive: true })
const server = createServer()
await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve))
let browser
const exports = []
try {
  browser = await chromium.launch({
    channel: process.env.BOOKS_BROWSER_CHANNEL || 'msedge',
    headless: true,
  })
  const context = await browser.newContext({ javaScriptEnabled: false })
  for (const volume of catalog.volumes) {
    const page = await context.newPage()
    const response = await page.goto(
      `http://127.0.0.1:${server.address().port}/books/${volume.id}/print.html`,
      { waitUntil: 'networkidle' },
    )
    if (response.status() !== 200) throw new Error(`Cannot print ${volume.id}`)
    await page.emulateMedia({ media: 'print' })
    await page.evaluate(async () => {
      document.querySelectorAll('img').forEach((img) => {
        img.loading = 'eager'
      })
      await document.fonts.ready
      await Promise.all([...document.images].map((img) => img.decode()))
    })
    const pdf = await page.pdf({
      path: path.join(directory, `${volume.id}.pdf`),
      format: 'A4',
      preferCSSPageSize: true,
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: '<span></span>',
      footerTemplate: `<div style="font-size:8px;color:#666;width:100%;text-align:center;">X-SIA · ${volume.title} · 编辑草案 &nbsp; <span class="pageNumber"></span> / <span class="totalPages"></span></div>`,
      tagged: true,
      outline: true,
    })
    if (!pdf.subarray(0, 5).equals(Buffer.from('%PDF-'))) throw new Error('Invalid PDF header')
    exports.push({
      volume: volume.id,
      title: volume.title,
      file: `${volume.id}.pdf`,
      bytes: pdf.length,
      sha256: createHash('sha256').update(pdf).digest('hex'),
    })
    await page.close()
  }
  await context.close()
  await writeFile(
    path.join(directory, 'manifest.json'),
    JSON.stringify(
      {
        edition: catalog.edition,
        sourceSha256: buildReport.sourceSha256,
        exportedAt: new Date().toISOString(),
        verification: 'Generated by Chromium print; not a full page-by-page publishing review.',
        exports,
      },
      null,
      2,
    ),
  )
  const finalReport = await build()
  if (finalReport.sourceSha256 !== buildReport.sourceSha256)
    throw new Error('Sources changed during export; re-export the PDFs')
  console.log(JSON.stringify(exports, null, 2))
} finally {
  await browser?.close()
  await new Promise((resolve) => server.close(resolve))
}
